config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  authenticate :employee do
    mount Sidekiq::Web => '/sidekiq'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # defaults to dashboard
  root :to => 'singleview#index'

  # view routes
  get '/singleview' => 'singleview#index'

  # api routes
  get '/api/i18n/:locale' => 'api#i18n'

  namespace :employee do
    root 'dashboard#welcome'
    resources :employments
    resources :patients do
      get :appointments, to: 'appointments#patient_appointments'
    end
    resources :employees do
      get :doctors, on: :collection
      resources :appointments, only: [:index, :edit]
      post 'appointments-doctors', on: :collection
      get 'appointments', on: :collection
      resources :day_schedules
      member do
        get 'work-schedule', to: 'employees#work_schedule'
      end
    end
    resources :appointments, only: [:create, :update, :destroy, :show] do
      post :generate_appointments, path: 'generate-appointments', on: :collection
      post :day_appointments, path: 'day-appointments', on: :collection
      get :summary, on: :member
      put :cancel, on: :member
      get :incoming, on: :collection
    end
    get :appointments, to: 'appointments#appointments'
    resources :medicines do
      get 'fetch-from-csv', on: :collection
      post 'parse-csv', on: :collection
    end
    resources :specific_diseases, path: 'specific-diseases', only: [:index, :edit, :show, :update, :destroy]
    resources :diseases, only: [:index, :show, :edit, :create, :destroy, :update] do
      collection do
        get :import
        get 'specific-diseases', to: 'diseases#specific_diseases'
        post 'parse-xml'
        get '/:id/new', to: 'diseases#new', as: :new
        get '/:id/details', to: 'diseases#details', as: :details
        get '/new', to: 'diseases#new', as: :new_root
        post '/:id', to: 'diseases#create', as: :create
        post '/', to: 'diseases#create', as: :create_root
        get '/:id/edit', to: 'diseases#edit', as: :edit
        #   get '/new', to: 'diseases#new', as: :new_root
        get '/edit', to: 'diseases#new', as: :edit_root
        #   get '/*code', to: 'diseases#show', as: :show
        #
      end

    end
    get 'reports/doctors'
    get 'reports/patients'
    post 'reports/patient_report'


  end

  namespace :patient do
    root 'dashboard#index'
    resources :appointments, only: [:index, :update] do
      get :make_appointment, on: :collection, path: 'make-appointment'
      post :day_appointments, on: :collection, path: 'day-appointments'
      put :cancel, on: :member
      get :summary, on: :member
    end
    resources :dashboard, only: [:index]
    resources :employees, except: [:index, :new, :create, :update, :edit, :destroy, :show] do
      get :work_schedules, on: :collection, path: 'work-schedules'
      get :show_work_schedule, on: :member, path: 'work-schedule'
      post :doctors_who_has_appointments, on: :collection, path: 'doctors-who-has-appointments'
      resources :day_schedules, only: [:index]
    end
    resources :medicines, only: [:index, :show]
    resources :diseases, only: [:index, :show] do
      collection do
        get '/:id/details', to: 'diseases#details', as: :details
      end
    end
    get 'reports/patients'
    post 'reports/patient_report'
  end
  devise_for :employees, path: 'employee', controllers: {sessions: 'employee/sessions'}
  devise_for :patients, path: 'patient', controllers: {sessions: 'patient/sessions'}

end

app/models/concerns/employee/appointments/manager.rb
module Employee::Appointments
  module Manager
    class << self
      def update(appointment, appointments_params)
        appointment.update!(appointments_params)
        appointment
      end

      def update_with_reminder(appointment, appointments_params)
        appointment.assign_attributes(appointments_params)
        if (appointments_params[:status].to_sym == :incoming or appointment.patient_id_changed?) and appointment.days_to_appointment >= 1
          PatientMailer.delay_until(appointment.planned_start - 1.day).appointment_reminder(appointment.id, appointment.patient.id)
        end
        appointment.save!
        appointment
      end

      def generate_appointmnets_for_month
        doctors = Employee.all.doctor
        today = Date.today
        (today..today + 30.days).each do |day|
          day_name = day.strftime("%A").downcase
          next if day_name == 'saturday' or day_name == 'sunday'
          doctors.each do |doctor|
            schedules_for_day = doctor.day_schedules.where(day: day_name)
            schedules_for_day = schedules_for_day.sort_by {|schedule| schedule.start_time.strftime("%H:%M")}
            schedules_for_day.each do |schedule|
              start_time = schedule.start_time
              next if Appointment.where('doctor_id = :doctor_id and planned_start::date = :date', doctor_id: doctor.id, date: Date.new(day.year, day.month, day.day)).present?
              while start_time < schedule.end_time do
                appointment_start = Time.new(day.year, day.month, day.day, start_time.hour, start_time.min)
                Appointment.find_or_create_by!(doctor: doctor, planned_start: appointment_start, planned_end: appointment_start + doctor.appointment_time.minutes, status: :empty)
                start_time += doctor.appointment_time.minutes

              end
            end
          end

        end
      end
    end
  end
end

app/models/concerns/employee/appointments/service.rb
  module Employee::Appointments
  module Service
    class << self
      def get_day_appointments(params)
        day = params[:day].to_datetime
        Appointment.where(planned_start: day.midnight..day.end_of_day, doctor: params[:doctor_id])
      end

      def get_incoming(params)
        appointments = Appointment.incoming.where(planned_start: Time.now.beginning_of_day..(Time.now + 30.days).end_of_day)
        appointments = appointments.where(doctor: params.doctor) if params.doctor.present?
        appointments = appointments.where(patient: params.patient) if params.patient.present?
        appointments
      end
    end
  end
end

app/models/concerns/employee/diseases/manager.rb
module Employee::Diseases
  module Manager
    class << self
      def create(disease_params)
        Disease.create!(disease_params)
      end

      def update(disease, disease_params)
        disease.update!(disease_params)
        disease
      end
    end
  end
end

app/controllers/employee/appointments_controller.rb
class Employee::AppointmentsController < Employee::BaseController
  load_and_authorize_resource :employee, only: [:index]
  authorize_resource
  before_action :find_appointment, only: [:update, :show, :edit, :summary, :destroy, :cancel]


  def index
    if params[:type] == 'ended'
      @appointments = @employee.doctor_appointments.ended.order(actual_end: :desc)
    else
      if @current_user.doctor?
        @appointments = @employee.doctor_appointments.incoming.where(planned_start: (Time.now.beginning_of_day - 7.days)..Time.now.end_of_day + 30.days).order(:planned_start)
        # @appointments = @employee.doctor_appointments.incoming.order(:planned_start)
      else
        @appointments = @employee.doctor_appointments.incoming.where(planned_start: (Time.now.beginning_of_day - 7.days)..Time.now.end_of_day + 30.days).order(:planned_start)
      end
    end
  end

  def day_appointments
    appointments = Employee::Appointments::Service.get_day_appointments day_appointments_params
    respond_to do |format|
      format.json {render json: appointments}
    end
  end

  def appointments
  end

  def edit
    @appointment.update!(actual_start: Time.now) unless params[:from_summary].present?
  end

  def show

  end

  def update
    respond_to do |format|
      format.json {
        appointment = Employee::Appointments::Manager.update_with_reminder @appointment, appointment_json_params
        render json: appointment

      }
      format.html {
        @appointment = Employee::Appointments::Manager.update @appointment, appointment_html_params.merge(actual_end: Time.now)
        if @appointment.status == 'incoming'
          redirect_to summary_employee_appointment_path(@appointment)
        else
          respond_with_success "Wizyta została zakończona", employee_employee_appointments_path(@appointment.doctor)
        end
      }

    end
  end

  def summary
    # if @appointment.status != 'ended'
    #   respond_with_error "Wystąpił błąd podczas przeprowadzania wizyty spróbój ponownie", employee_employee_appointments_path(@appointment.doctor)
    # end
    #
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'summary' # Excluding ".pdf" extension.
      end
    end
  end

  def patient_appointments
    respond_to do |format|
      format.json {render json: PatientAppointmentsDatatable.new(view_context, @current_ability)}
    end
  end

  def generate_appointments
    Employee::Appointments::Manager.generate_appointmnets_for_month
    respond_with_success "Wizyty na następny miesąć zostały wygenerowane", employee_root_path
  end

  def destroy
    @appointment.destroy!
    respond_with_success "Wizyty została pomyślnie usunięta", employee_employee_appointments_path(@appointment.doctor)
  end

  def incoming
    @incoming_filter = OpenStruct.new(doctor: incoming_appointments_params[:doctor], patient: incoming_appointments_params[:patient])
    @appointments = Employee::Appointments::Service.get_incoming @incoming_filter
  end

  def cancel
    Patient::Appointments::Manager.cancel(@appointment)
    respond_with_success "Wizyty została pomyślnie odwołana", request.referrer
  end

  private

  def appointment_json_params
    params.permit(:patient_id, :description, :status)
  end

  def appointment_html_params
    params.require(:appointment).permit(:doctor, :patient, :patient_id, :doctor_comment, :description, :status, appointment_diseases_attributes: [:id, :_destroy, :disease_code], prescriptions_attributes: [:id, :_destroy, :employee_id, :patient_id, :description, prescription_medicines_attributes: [:id, :_destroy, :quantity, :comment, :medicine_id]])
  end

  def incoming_appointments_params
    params.fetch(:@incoming_filter, {}).permit(:patient, :doctor)
  end

  def find_appointment
    @appointment = Appointment.find(params[:id])
  end

  def day_appointments_params
    params.permit(:day, :doctor_id)
  end
end

app/controllers/employee/base_controller.rb
class Employee::BaseController < ApplicationController
  before_action :authenticate_employee!
  before_action :check_if_employee

  def check_if_employee
    if current_patient
      flash.clear
      # if you have rails_admin. You can redirect anywhere really
      redirect_to(root_path) && return
    end
  end
end

app/controllers/employee/dashboard_controller.rb
class Employee::DashboardController < Employee::BaseController
  def welcome
    if current_employee.admin?
      redirect_to employee_appointments_path
    elsif current_employee.doctor?
      redirect_to employee_employee_appointments_path current_employee
    else
      redirect_to employee_appointments_path
    end
  end
end

app/controllers/employee/day_schedules_controller.rb
class Employee::DaySchedulesController < Employee::BaseController
  before_action :find_employee
  before_action :find_day_schedule, only: [:edit, :update, :show, :destroy]

  def index
    @day_schedules = @employee.day_schedules

  end

  def show
  end

  def new
    @day_schedule = @employee.day_schedules.new
  end

  def create
    @day_schedule = @employee.day_schedules.new(day_schedule_params)
    @day_schedule.save!
  end

  def edit

  end

  def update
    @day_schedule.update(day_schedule_params)
  end

  def destroy
    @day_schedule.destroy
  end

  private
  def find_day_schedule
    @day_schedule = DaySchedule.find_by(id: params[:id])
  end

  def find_employee
    @employee = Employee.find_by(id: params[:employee_id])
  end

  def day_schedule_params
    params.require(:day_schedule).permit(:employee_id, :start_time, :end_time, :day)
  end
end

app/controllers/employee/diseases_controller.rb
class Employee::DiseasesController < Employee::BaseController
  authorize_resource
  before_action :find_disease_by_id, only: [:destroy, :show, :new, :update, :edit, :details]

  def index
    @diseases = Disease.roots.order(:code)
  end

  def show
    @diseases = @disease.children.order(:code)
  end

  def new
    if @disease.present?
      @disease = @disease.children.build
    else
      @disease = Disease.new
    end
  end

  def create
    disease = Employee::Diseases::Manager.create(disease_params)
    respond_with_success "Choroba została pomyślnie utworzona", disease.parent.present? ? employee_disease_path(disease.parent) : employee_diseases_path
  end

  def edit

  end

  def update
    disease = Employee::Diseases::Manager.update(@disease, disease_params)
    respond_with_success "Choroba została pomyślnie zaktualizowana", disease.parent.present? ? employee_disease_path(disease.parent) : employee_diseases_path
  end

  def destroy
    parent = @disease.parent
    @disease.destroy!
    respond_with_success "Choroba została pomyślnie usunięta", parent.present? ? employee_disease_path(parent) : employee_diseases_path
  end

  def details

  end

  def parse_xml
    Employee::DiseasesCategories::Manager.parse_xml import_params
    respond_with_success 'Baza chorób została zaktualizowana', employee_diseases_path
  end

  def import

  end

  def specific_diseases
    @specific_diseases = Disease.where('lower(name) like ? or lower(code) like ?', "%#{params[:selectSearch].downcase}%", "%#{params[:selectSearch].downcase}%")
    respond_to do |format|

      format.json {
        render json: @specific_diseases
      }

    end
  end

  private

  def import_params
    params.permit(:file, :disease_update_url)
  end

  def find_disease_by_id
    @disease = Disease.friendly.find(params[:id]) if params[:id].present?
  end

  def disease_params
    params.require(:disease).permit(:name, :code, :parent_id, :description)
  end
end

app/controllers/employee/employees_controller.rb
class Employee::EmployeesController < Employee::BaseController
  authorize_resource
  before_action :find_employee, only: [:show, :edit, :update, :destroy, :work_schedule]

  def index
    @employees = Employee.all
  end

  def doctors
    @doctors = Employee.doctor
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def work_schedule

  end

  def create
    if Employee.find_by(email: employee_params[:email]).present?
      respond_with_error "Pracownik o podanym emailu już istnieje", employee_employees_path
    else
      Employee::Employees::Manager.create employee_params
      respond_with_success "Pracownik został pomyślnie dodany. Na podany email zostało wysłane hasło.", employee_employees_path
    end
  end

  def update
    if @employee.update(employee_params)
      respond_common_to_action employee_employees_path, error: false
    else
      respond_common_to_action employee_employees_path, error: true
    end
  end


  def destroy
    if @employee.destroy
      respond_common_to_action employee_employees_path, error: false
    else
      respond_common_to_action employee_employees_path, error: true
    end

  end

  def appointments
    @doctors = Employee.doctor.has_appointments.uniq
  end

  def appointments_doctors
    day = appointments_doctors_params[:day].to_date
    @doctors = Employee.doctor.has_appointments_in_day(day)
    respond_to do |format|
      format.json {render json: @doctors}
    end
  end

  private
  def find_employee
    @employee = Employee.find(params[:id])
    raise NotFound if @employee.blank?
  end

  def employee_params
    params.require(:employee).permit(:first_name, :email, :last_name, :pesel, :role, :phone_number, :appointment_time)
  end

  def appointments_doctors_params
    params.permit(:day)
  end
end

app/controllers/employee/medicines_controller.rb
class Employee::MedicinesController < Employee::BaseController
  authorize_resource
  before_action :find_medicine, only: [:edit, :update, :destroy, :show]


  def index
    respond_to do |format|
      format.html
      format.json {
        if params[:start].present?
          render json: MedicinesDatatable.new(view_context)
        else
          render json: Medicine.where('lower(name) like :search or lower(common_name) like :search', search: "%#{params[:selectSearch].downcase}%")
        end
      }
    end
  end

  def new
    @medicine = Medicine.new
  end

  def create
    medicine = Employee::Medicines::Manager.create medicine_params
    if medicine.present?
      respond_common_to_action employee_medicines_path, error: false
    else
      respond_common_to_action employee_medicines_path, error: true
    end

  end

  def edit
  end

  def update
    Employee::Medicines::Manager.update @medicine, medicine_params
    respond_with_success " Lek został pomyślnie zaktualizowany ", employee_medicines_path
  end

  def destroy
    Employee::Medicines::Manager.destroy @medicine
    respond_with_success " Lek został pomyślnie usunięty ", employee_medicines_path
  end

  def show
  end

  def fetch_from_csv

  end

  def parse_csv
    Employee::Medicines::Service.parse_csv_medicines(parse_csv_params)
    respond_with_success 'Baza lekarstw została zaktualizowana', employee_medicines_path
  end

  private

  def find_medicine
    @medicine = Medicine.find(params[:id])
    raise NotFound if @medicine.blank?
  end

  def medicine_params
    params.require(:medicine).permit(:name, :common_name, :strength, :active_substance, :form, :marketing_holder, :package)
  end

  def parse_csv_params
    params.permit(:medicines_update_url, :file)

  end
end

app/views/layouts/partials/menu/employee/_admin_menu.html.erb
<!-- START sidebar nav-->
<ul class="nav">
  <li class="nav-heading">
    <span>Menu administratora</span>
  </li>
  <li class="<%= 'active' if controller?('employee/appointments') %>">
    <a href="#appointments" title="Wizyty" data-toggle="collapse">
      <em class="icon-pencil"></em>
      <span>Wizyty</span>
    </a>
    <ul id="appointments" class="nav sidebar-subnav collapse">
      <li class="sidebar-subnav-header">Wizyty</li>
      <li class="<%= 'active' if controller?('employee/appointments') && action?('appointments') %>">
        <%= link_to 'Zarządzaj wizytami', employee_appointments_path %>
      </li>
      <li class="<%= 'active' if (controller?('employee/employees') && action?('appointments')) or (controller?('employee/appointments') && action?('index')) %>">
        <%= link_to 'Wizyty lekarzy', appointments_employee_employees_path %>
      </li>
      <li class="<%= 'active' if (controller?('employee/appointments') && action?('incoming')) %>">
        <%= link_to 'Nadchodzące wizyty', incoming_employee_appointments_path %>
      </li>
    </ul>
  </li>

  <li class="<%= 'active' if controller?('maps') %>">
    <a href="#struct" title="Struktura" data-toggle="collapse">
      <em class="icon-people"></em>
      <span>Ludzie</span>
    </a>
    <ul id="struct" class="nav sidebar-subnav collapse">
      <li class="sidebar-subnav-header">Ludzie</li>
      <li class="<%= 'active' if controller?('employee/employees') and !action?('appointments') %>">
        <%= link_to 'Pracownicy', employee_employees_path %>
      </li>
      <li class="<%= 'active' if controller?('employee/patients') %>">
        <%= link_to 'Pacjenci', employee_patients_path %>
      </li>
    </ul>
  </li>
  <li class="<%= 'active' if controller?('employee/medicines') or controller?('employee/diseases') %>">
    <a href="#dictionares" title="Struktura" data-toggle="collapse">
      <em class="icon-notebook"></em>
      <span>Słowniki</span>
    </a>
    <ul id="dictionares" class="nav sidebar-subnav collapse">
      <li class="sidebar-subnav-header">Słowniki</li>
      <li class="<%= 'active' if controller?('employee/medicines') %>">
        <%= link_to 'Produkty medyczne', employee_medicines_path %>
      </li>
      <li class="<%= 'active' if controller?('employee/diseases') %>">
        <%= link_to 'Choroby ICD-10', employee_diseases_path %>
      </li>
    </ul>
  </li>
  <li class="<%= 'active' if controller?('employee/reports') %>">
    <a href="#reports" title="Struktura" data-toggle="collapse">
      <em class="icon-pie-chart"></em>
      <span>Raporty</span>
    </a>
    <ul id="reports" class="nav sidebar-subnav collapse">
      <li class="sidebar-subnav-header">Raporty</li>
      <li class="<%= 'active' if controller?('employee/reports') and action?('doctors') %>">
        <%= link_to 'Raport lekarzy', employee_reports_doctors_path %>
      </li>
      <li class="<%= 'active' if controller?('employee/reports') and action?('patients') %>">
        <%= link_to 'Raport pacjentów', employee_reports_patients_path %>
      </li>
    </ul>
  </li>
</ul>
<!-- END sidebar nav-->

app/views/layouts/partials/menu/employee/_doctor_menu.html.erb
<ul class="nav">
  <li class="nav-heading">
    <span>Menu lekarza</span>
  </li>
  <li class="<%= 'active' if controller?('employee/appointments') && (action?('index') or action?('summary')) %>">
    <%= navigation_link employee_employee_appointments_path(current_employee), 'Wizyty', 'icon-notebook' %>
  </li>

  <li class="<%= 'active' if controller?('employee/medicines') %>">
    <%= navigation_link employee_medicines_path, 'Leki', 'icon-heart' %>
  </li>

  <li class="<%= 'active' if controller?('employee/diseases_categories') or controller?('employee/diseases_subcategories') or controller?('employee/main_diseases') or controller?('employee/diseases') %>">
    <%= navigation_link employee_diseases_path, 'Choroby ICD-10', 'icon-book-open' %>
  </li>

  <li class="<%= 'active' if controller?('employee/patients') %>">
    <%= navigation_link employee_patients_path, 'Pacjenci', 'icon-people' %>
  </li>

  <li class="<%= 'active' if controller?('employee/reports') %>">
    <a href="#reports" title="Struktura" data-toggle="collapse">
      <em class="icon-pie-chart"></em>
      <span>Raporty</span>
    </a>
    <ul id="reports" class="nav sidebar-subnav collapse">
      <li class="sidebar-subnav-header">Raporty</li>
      <li class="<%= 'active' if controller?('employee/reports') and action?('doctors') %>">
        <%= link_to 'Raport lekarzy', employee_reports_doctors_path %>
      </li>
      <li class="<%= 'active' if controller?('employee/reports') and action?('patients') %>">
        <%= link_to 'Raport pacjentów', employee_reports_patients_path %>
      </li>
    </ul>
  </li>


</ul>

app/views/layouts/partials/menu/employee/_receptionist_menu.html.erb
<ul class="nav">
  <li class="nav-heading">
    <span>Menu recepcji</span>
  </li>
  <li class="<%= 'active' if controller?('employee/appointments') and action?('appointments') %>">
    <%= navigation_link employee_appointments_path, 'Zarządzaj wizytami', 'icon-notebook' %>
  </li>
  <li class="<%= 'active' if (controller?('employee/appointments') && action?('incoming')) %>">
    <%= navigation_link incoming_employee_appointments_path, 'Nadchodzące wizyty', 'icon-clock' %>
  </li>
  <li class="<%= 'active' if controller?('employee/patients') %>">
    <%= navigation_link employee_patients_path, 'Pacjenci', 'icon-people' %>
  </li>
  <li class="<%= 'active' if controller?('employee/employees') and action?('doctors') %>">
    <%= navigation_link doctors_employee_employees_path, 'Grafiki lekarzy', 'icon-calendar' %>
  </li>
  <li class="<%= 'active' if controller?('employee/reports') and action?('patients') %>">
    <%= navigation_link employee_reports_patients_path, 'Raport pacjentów', 'icon-pie-chart' %>
  </li>


</ul>