config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  authenticate :employee do
    mount Sidekiq::Web => '/sidekiq'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # defaults to dashboard
  root :to => 'singleview#index'

  # view routes
  get '/singleview' => 'singleview#index'

  # api routes
  get '/api/i18n/:locale' => 'api#i18n'

  namespace :employee do
    root 'dashboard#welcome'
    resources :employments
    resources :patients do
      get :appointments, to: 'appointments#patient_appointments'
    end
    resources :employees do
      get :doctors, on: :collection
      resources :appointments, only: [:index, :edit]
      post 'appointments-doctors', on: :collection
      get 'appointments', on: :collection
      resources :day_schedules
      member do
        get 'work-schedule', to: 'employees#work_schedule'
      end
    end
    resources :appointments, only: [:create, :update, :destroy, :show] do
      post :generate_appointments, path: 'generate-appointments', on: :collection
      post :day_appointments, path: 'day-appointments', on: :collection
      get :summary, on: :member
      put :cancel, on: :member
      get :incoming, on: :collection
    end
    get :appointments, to: 'appointments#appointments'
    resources :medicines do
      get 'fetch-from-csv', on: :collection
      post 'parse-csv', on: :collection
    end
    resources :specific_diseases, path: 'specific-diseases', only: [:index, :edit, :show, :update, :destroy]
    resources :diseases, only: [:index, :show, :edit, :create, :destroy, :update] do
      collection do
        get :import
        get 'specific-diseases', to: 'diseases#specific_diseases'
        post 'parse-xml'
        get '/:id/new', to: 'diseases#new', as: :new
        get '/:id/details', to: 'diseases#details', as: :details
        get '/new', to: 'diseases#new', as: :new_root
        post '/:id', to: 'diseases#create', as: :create
        post '/', to: 'diseases#create', as: :create_root
        get '/:id/edit', to: 'diseases#edit', as: :edit
        #   get '/new', to: 'diseases#new', as: :new_root
        get '/edit', to: 'diseases#new', as: :edit_root
        #   get '/*code', to: 'diseases#show', as: :show
        #
      end

    end
    get 'reports/doctors'
    get 'reports/patients'
    post 'reports/patient_report'


  end

  namespace :patient do
    root 'dashboard#index'
    resources :appointments, only: [:index, :update] do
      get :make_appointment, on: :collection, path: 'make-appointment'
      post :day_appointments, on: :collection, path: 'day-appointments'
      put :cancel, on: :member
      get :summary, on: :member
    end
    resources :dashboard, only: [:index]
    resources :employees, except: [:index, :new, :create, :update, :edit, :destroy, :show] do
      get :work_schedules, on: :collection, path: 'work-schedules'
      get :show_work_schedule, on: :member, path: 'work-schedule'
      post :doctors_who_has_appointments, on: :collection, path: 'doctors-who-has-appointments'
      resources :day_schedules, only: [:index]
    end
    resources :medicines, only: [:index, :show]
    resources :diseases, only: [:index, :show] do
      collection do
        get '/:id/details', to: 'diseases#details', as: :details
      end
    end
    get 'reports/patients'
    post 'reports/patient_report'
  end
  devise_for :employees, path: 'employee', controllers: {sessions: 'employee/sessions'}
  devise_for :patients, path: 'patient', controllers: {sessions: 'patient/sessions'}

end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient, optional: true
  has_many :prescriptions, dependent: :destroy
  belongs_to :doctor, class_name: 'Employee'
  belongs_to :receptionist, class_name: 'Employee', optional: true
  has_many :appointment_diseases, dependent: :destroy
  has_many :diseases, through: :appointment_diseases, dependent: :destroy
  enum status: [:empty, :incoming, :ended]
  accepts_nested_attributes_for :prescriptions, allow_destroy: true
  accepts_nested_attributes_for :appointment_diseases, allow_destroy: true

  scope :by_date, ->(start_date, end_date) {where(actual_start: start_date..end_date)}
  scope :by_doctor, ->(doctor_id) {where(doctor: doctor_id)}
  scope :by_patient, ->(patient_id) {where(patient: patient_id)}


  def days_to_appointment
    ((Time.now - self.planned_start) / 1.day).to_i
  end

  def medicines
    medicines_id = PrescriptionMedicine.where(prescription_id: self.prescriptions.map {|p| p.id}).map {|pm| pm.medicine_id}
    Medicine.where(id:medicines_id)
  end

end

app/models/concerns/employee/appointments/manager.rb
module Employee::Appointments
  module Manager
    class << self
      def update(appointment, appointments_params)
        appointment.update!(appointments_params)
        appointment
      end

      def update_with_reminder(appointment, appointments_params)
        appointment.assign_attributes(appointments_params)
        if (appointments_params[:status].to_sym == :incoming or appointment.patient_id_changed?) and appointment.days_to_appointment >= 1
          PatientMailer.delay_until(appointment.planned_start - 1.day).appointment_reminder(appointment.id, appointment.patient.id)
        end
        appointment.save!
        appointment
      end

      def generate_appointmnets_for_month
        doctors = Employee.all.doctor
        today = Date.today
        (today..today + 30.days).each do |day|
          day_name = day.strftime("%A").downcase
          next if day_name == 'saturday' or day_name == 'sunday'
          doctors.each do |doctor|
            schedules_for_day = doctor.day_schedules.where(day: day_name)
            schedules_for_day = schedules_for_day.sort_by {|schedule| schedule.start_time.strftime("%H:%M")}
            schedules_for_day.each do |schedule|
              start_time = schedule.start_time
              next if Appointment.where('doctor_id = :doctor_id and planned_start::date = :date', doctor_id: doctor.id, date: Date.new(day.year, day.month, day.day)).present?
              while start_time < schedule.end_time do
                appointment_start = Time.new(day.year, day.month, day.day, start_time.hour, start_time.min)
                Appointment.find_or_create_by!(doctor: doctor, planned_start: appointment_start, planned_end: appointment_start + doctor.appointment_time.minutes, status: :empty)
                start_time += doctor.appointment_time.minutes

              end
            end
          end

        end
      end
    end
  end
end

app/models/concerns/employee/appointments/service.rb
  module Employee::Appointments
  module Service
    class << self
      def get_day_appointments(params)
        day = params[:day].to_datetime
        Appointment.where(planned_start: day.midnight..day.end_of_day, doctor: params[:doctor_id])
      end

      def get_incoming(params)
        appointments = Appointment.incoming.where(planned_start: Time.now.beginning_of_day..(Time.now + 30.days).end_of_day)
        appointments = appointments.where(doctor: params.doctor) if params.doctor.present?
        appointments = appointments.where(patient: params.patient) if params.patient.present?
        appointments
      end
    end
  end
end

app/models/concerns/employee/diseases/manager.rb
module Employee::Diseases
  module Manager
    class << self
      def create(disease_params)
        Disease.create!(disease_params)
      end

      def update(disease, disease_params)
        disease.update!(disease_params)
        disease
      end
    end
  end
end

app/models/concerns/employee/diseases_subcategories/manager.rb
module Employee::DiseasesSubcategories
  module Manager
    class << self
      def create(diseases_category, diseases_subcategory_params)
        diseases_category.diseases_subcategories.create!(diseases_subcategory_params)
      end

      def update(diseases_subcategory, diseases_subcategory_params)
        diseases_subcategory.update!(diseases_subcategory_params)
        diseases_subcategory
      end

      def destroy(diseases_subcategory)
        diseases_subcategory.destroy!
      end
    end
  end
end

app/models/concerns/employee/employees/manager.rb
module Employee::Employees
  module Manager
    class << self
      def create(employee_params)
        generated_password = Devise.friendly_token.first(8)
        employee_params.merge!(:password => generated_password)
        employee = Employee.create!(employee_params)
        EmployeeMailer.after_create(employee.id, generated_password).deliver_later if employee.present?
        employee
      end
    end
  end
end

app/models/concerns/employee/main_diseases/manager.rb
module Employee::MainDiseases
  module Manager
    class << self
      def create(diseases_subcategory, main_disease_params)
        diseases_subcategory.main_diseases.create!(main_disease_params)
      end

      def update(main_disease, main_disease_params)
        main_disease.update!(main_disease_params)
        main_disease
      end

      def destroy(main_disease)
        main_disease.destroy!
      end
    end
  end
end

app/models/concerns/employee/medicines/manager.rb
module Employee::Medicines
  module Manager
    class << self
      def create(medicine_params)
        Medicine.create!(medicine_params)
      end

      def update(medicine, medicine_params)
        medicine.update!(medicine_params)
        medicine
      end

      def destroy(medicine)
        medicine.destroy
      end
    end
  end
end

app/models/concerns/employee/patients/manager.rb
module Employee::Patients
  module Manager
    class << self
      def create(patient_params)
        password = Devise.friendly_token.first(8)
        patient_params.merge!(password: password)
        patient = Patient.create!(patient_params)
        PatientMailer.after_create(patient.id, password).deliver_later if patient.present?
        patient
      end

      def update(patient, patient_params)
        patient.update patient_params
      end
    end
  end
end

app/controllers/employee/appointments_controller.rb
class Employee::AppointmentsController < Employee::BaseController
  load_and_authorize_resource :employee, only: [:index]
  authorize_resource
  before_action :find_appointment, only: [:update, :show, :edit, :summary, :destroy, :cancel]


  def index
    if params[:type] == 'ended'
      @appointments = @employee.doctor_appointments.ended.order(actual_end: :desc)
    else
      if @current_user.doctor?
        @appointments = @employee.doctor_appointments.incoming.where(planned_start: (Time.now.beginning_of_day - 7.days)..Time.now.end_of_day + 30.days).order(:planned_start)
        # @appointments = @employee.doctor_appointments.incoming.order(:planned_start)
      else
        @appointments = @employee.doctor_appointments.incoming.where(planned_start: (Time.now.beginning_of_day - 7.days)..Time.now.end_of_day + 30.days).order(:planned_start)
      end
    end
  end

  def day_appointments
    appointments = Employee::Appointments::Service.get_day_appointments day_appointments_params
    respond_to do |format|
      format.json {render json: appointments}
    end
  end

  def appointments
  end

  def edit
    @appointment.update!(actual_start: Time.now) unless params[:from_summary].present?
  end

  def show

  end

  def update
    respond_to do |format|
      format.json {
        appointment = Employee::Appointments::Manager.update_with_reminder @appointment, appointment_json_params
        render json: appointment

      }
      format.html {
        @appointment = Employee::Appointments::Manager.update @appointment, appointment_html_params.merge(actual_end: Time.now)
        if @appointment.status == 'incoming'
          redirect_to summary_employee_appointment_path(@appointment)
        else
          respond_with_success "Wizyta została zakończona", employee_employee_appointments_path(@appointment.doctor)
        end
      }

    end
  end

  def summary
    # if @appointment.status != 'ended'
    #   respond_with_error "Wystąpił błąd podczas przeprowadzania wizyty spróbój ponownie", employee_employee_appointments_path(@appointment.doctor)
    # end
    #
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'summary' # Excluding ".pdf" extension.
      end
    end
  end

  def patient_appointments
    respond_to do |format|
      format.json {render json: PatientAppointmentsDatatable.new(view_context, @current_ability)}
    end
  end

  def generate_appointments
    Employee::Appointments::Manager.generate_appointmnets_for_month
    respond_with_success "Wizyty na następny miesąć zostały wygenerowane", employee_root_path
  end

  def destroy
    @appointment.destroy!
    respond_with_success "Wizyty została pomyślnie usunięta", employee_employee_appointments_path(@appointment.doctor)
  end

  def incoming
    @incoming_filter = OpenStruct.new(doctor: incoming_appointments_params[:doctor], patient: incoming_appointments_params[:patient])
    @appointments = Employee::Appointments::Service.get_incoming @incoming_filter
  end

  def cancel
    Patient::Appointments::Manager.cancel(@appointment)
    respond_with_success "Wizyty została pomyślnie odwołana", request.referrer
  end

  private

  def appointment_json_params
    params.permit(:patient_id, :description, :status)
  end

  def appointment_html_params
    params.require(:appointment).permit(:doctor, :patient, :patient_id, :doctor_comment, :description, :status, appointment_diseases_attributes: [:id, :_destroy, :disease_code], prescriptions_attributes: [:id, :_destroy, :employee_id, :patient_id, :description, prescription_medicines_attributes: [:id, :_destroy, :quantity, :comment, :medicine_id]])
  end

  def incoming_appointments_params
    params.fetch(:@incoming_filter, {}).permit(:patient, :doctor)
  end

  def find_appointment
    @appointment = Appointment.find(params[:id])
  end

  def day_appointments_params
    params.permit(:day, :doctor_id)
  end
end

app/controllers/employee/base_controller.rb
class Employee::BaseController < ApplicationController
  before_action :authenticate_employee!
  before_action :check_if_employee

  def check_if_employee
    if current_patient
      flash.clear
      # if you have rails_admin. You can redirect anywhere really
      redirect_to(root_path) && return
    end
  end
end

app/controllers/employee/dashboard_controller.rb
class Employee::DashboardController < Employee::BaseController
  def welcome
    if current_employee.admin?
      redirect_to employee_appointments_path
    elsif current_employee.doctor?
      redirect_to employee_employee_appointments_path current_employee
    else
      redirect_to employee_appointments_path
    end
  end
end

app/controllers/employee/day_schedules_controller.rb
class Employee::DaySchedulesController < Employee::BaseController
  before_action :find_employee
  before_action :find_day_schedule, only: [:edit, :update, :show, :destroy]

  def index
    @day_schedules = @employee.day_schedules

  end

  def show
  end

  def new
    @day_schedule = @employee.day_schedules.new
  end

  def create
    @day_schedule = @employee.day_schedules.new(day_schedule_params)
    @day_schedule.save!
  end

  def edit

  end

  def update
    @day_schedule.update(day_schedule_params)
  end

  def destroy
    @day_schedule.destroy
  end

  private
  def find_day_schedule
    @day_schedule = DaySchedule.find_by(id: params[:id])
  end

  def find_employee
    @employee = Employee.find_by(id: params[:employee_id])
  end

  def day_schedule_params
    params.require(:day_schedule).permit(:employee_id, :start_time, :end_time, :day)
  end
end

app/controllers/employee/diseases_controller.rb
class Employee::DiseasesController < Employee::BaseController
  authorize_resource
  before_action :find_disease_by_id, only: [:destroy, :show, :new, :update, :edit, :details]

  def index
    @diseases = Disease.roots.order(:code)
  end

  def show
    @diseases = @disease.children.order(:code)
  end

  def new
    if @disease.present?
      @disease = @disease.children.build
    else
      @disease = Disease.new
    end
  end

  def create
    disease = Employee::Diseases::Manager.create(disease_params)
    respond_with_success "Choroba została pomyślnie utworzona", disease.parent.present? ? employee_disease_path(disease.parent) : employee_diseases_path
  end

  def edit

  end

  def update
    disease = Employee::Diseases::Manager.update(@disease, disease_params)
    respond_with_success "Choroba została pomyślnie zaktualizowana", disease.parent.present? ? employee_disease_path(disease.parent) : employee_diseases_path
  end

  def destroy
    parent = @disease.parent
    @disease.destroy!
    respond_with_success "Choroba została pomyślnie usunięta", parent.present? ? employee_disease_path(parent) : employee_diseases_path
  end

  def details

  end

  def parse_xml
    Employee::DiseasesCategories::Manager.parse_xml import_params
    respond_with_success 'Baza chorób została zaktualizowana', employee_diseases_path
  end

  def import

  end

  def specific_diseases
    @specific_diseases = Disease.where('lower(name) like ? or lower(code) like ?', "%#{params[:selectSearch].downcase}%", "%#{params[:selectSearch].downcase}%")
    respond_to do |format|

      format.json {
        render json: @specific_diseases
      }

    end
  end

  private

  def import_params
    params.permit(:file, :disease_update_url)
  end

  def find_disease_by_id
    @disease = Disease.friendly.find(params[:id]) if params[:id].present?
  end

  def disease_params
    params.require(:disease).permit(:name, :code, :parent_id, :description)
  end
end

app/views/employee/appointments/_appointment.html.erb
<tr class="bb">
  <td class="b0 wd-xs text-center">
    <% if params[:type] == 'ended' %>
      <p><strong><%= appointment.actual_end.localtime.strftime("%d-%m-%Y %H:%M") %></strong></p>
    <% else %>
      <p><strong><%= appointment.planned_start.localtime.strftime("%d-%m-%Y %H:%M") %></strong></p>
    <% end %>
  </td>
  <td class="b0 wd-xs hidden-xs">
    <a href="#">
      <img src="<%= image_path('angle/appointment.png') %>" class="img-responsive thumb64"/>
    </a>
  </td>
  <td class="b0">
    <p class="h4 mt0">
      <% if appointment.status == 'incoming' %>
        <%= link_to time_diference_incoming(Time.now, appointment.planned_start.localtime), appointment_name_link(appointment), class: 'align-middle text-bold link-unstyled' %>
      <% else %>
        <%= link_to "Wizyta zakończona", appointment_name_link(appointment), class: 'align-middle text-bold link-unstyled' %>

      <% end %>
    </p>
    <small class="text-muted"><strong>Opis:</strong> <%= appointment.description %>
      <br/>
      <strong> Pacjent</strong>
      - <%= link_to appointment.patient.full_name, employee_patient_path(appointment.patient), class: "text-bold", target: "_blank" %>
    </small>
  </td>
  <td class="b0">
    <div class="row pull-right">
      <% if can? :delete, appointment %>
        <%= link_to 'Usuń wizytę', [:employee, appointment], method: :delete, class: 'btn btn-danger btn-xs', data: {confirm: "Jesteś pewien?"} %>
      <% end %>
      <% if can? :cancel, appointment %>
        <%= link_to 'Odwołaj wizytę', cancel_employee_appointment_path(appointment), method: :put, class: 'btn btn-danger btn-xs', data: {confirm: "Jesteś pewien?"} %>
      <% end %>
    </div>
  </td>
</tr>

app/views/employee/appointments/_incoming_appointment.html.erb
<tr class="bb">
  <td class="b0 wd-xs text-center">

    <p><strong><%= incoming_appointment.planned_start.localtime.strftime("%d-%m-%Y %H:%M") %></strong></p>

  </td>
  <td class="b0 wd-xs hidden-xs">
    <a href="#">
      <img src="<%= image_path('angle/appointment.png') %>" class="img-responsive thumb64"/>
    </a>
  </td>
  <td class="b0">
    <p class="h4 mt0 align-middle text-bold link-unstyled">
      <%=  time_diference_incoming(Time.now, incoming_appointment.planned_start.localtime)%>

    </p>
    <small class="text-muted"><strong>Opis:</strong> <%= incoming_appointment.description %>
      <br/>
      <strong>Pacjent</strong>
      - <%= link_to incoming_appointment.patient.full_name, employee_patient_path(incoming_appointment.patient), class: "text-bold" %>
      <br/>
      <strong>Lekarz</strong>
      - <%= incoming_appointment.doctor.full_name %>
    </small>
  </td>
  <td class="b0">
    <% if can? :cancel, incoming_appointment %>
      <div class="row pull-right">
        <%= link_to 'Odwołaj wizytę', cancel_employee_appointment_path(incoming_appointment), method: :put, class: 'btn btn-danger btn-xs', data: {confirm: "Jesteś pewien?"} %>
      </div>
    <% end %>
  </td>
</tr>

app/views/employee/appointments/appointments.html.erb
<%= react_component("employee/appointments/AppointmentsLayout") %>

app/views/employee/appointments/edit.html.erb
<div class="content-heading">
  <div class="clearfix">
    <div class="pull-left">
      Przeprowadz wizytę
      <br/>
      <small>
        <small>Uzupełnij dane</small>
      </small>
    </div>
    <div class="pull-right">
      <div class="btn-group">
        <%= angle_back_link employee_employee_appointments_path(@appointment.doctor) %>
      </div>
    </div>
  </div>
</div>

<!-- START panel-->
<div class="panel panel-default">
  <div class="panel-heading"><h4>Przeprowadz wizytę
    [Pacjent <%= link_to @appointment.patient.full_name, employee_reports_patients_path(patient: @appointment.patient.id), target: '_blank' %>
    ]</h4>
  </div>


  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/employee/appointments/summary.html.erb
<div class="content-heading">
  <div class="clearfix">
    <div class="pull-left">
      Podsumowanie wizyty
      <br/>
      <% if @appointment.status == 'incoming' %>
        <small>
          <small>Sprawdz czy wszystkie dane się zgadzają</small>
        </small>
      <% end %>
    </div>
    <div class="pull-right">
      <% if @appointment.status == 'incoming' %>
        <%= angle_back_link edit_employee_employee_appointment_path(@appointment.doctor, @appointment, from_summary: true), "Popraw informacje w wizycie" %>
      <% end %>
      <%= link_to 'Generuj PDF', summary_employee_appointment_path(@appointment, format: 'pdf'), class: "btn btn-success", target: '_blank' %>
    </div>
  </div>
</div>

<!-- START panel-->
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
      <div class="panel b">
        <div class="panel-heading bg-gray-lighter text-bold">Wybierz zakładkę</div>
        <div class="list-group">
          <a href="#tabSetting1" data-toggle="tab" class="list-group-item">Informacje ogólne</a>
          <a href="#tabSetting2" data-toggle="tab" class="list-group-item">Rozpoznane choroby</a>
          <a href="#tabSetting3" data-toggle="tab" class="list-group-item">Wypisane recepty</a>

        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="tab-content p0 b0">
        <div id="tabSetting1" class="tab-pane active">
          <div class="panel b">
            <div class="panel-heading bg-gray-lighter text-bold">Informacje ogólne</div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-6 col-xs-12">
                  <div class="panel b">
                    <div class="panel-heading">
                      <h4 class="m0">Wizyta</h4>
                      <small class="text-muted"><%= "Lekarz prowadzący: #{@appointment.doctor.full_name}" %></small>
                    </div>
                    <table class="table">
                      <tbody>
                      <tr>
                        <td>
                          <strong>Planowane rozpoczęcie wizyty:</strong>
                        </td>
                        <td><%= @appointment.planned_start.try(:localtime).try(:strftime, "%d-%m-%Y %H:%M") %></td>
                      </tr>
                      <tr>
                        <td>
                          <strong>Planowane zakończenie wizyty:</strong>
                        </td>
                        <td>
                          <%= @appointment.planned_end.try(:localtime).try(:strftime, "%d-%m-%Y %H:%M") %>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <strong>Rzeczywiste rozpoczęcie wizyty:</strong>
                        </td>
                        <td><%= @appointment.actual_start.try(:localtime).try(:strftime, "%d-%m-%Y %H:%M") %></td>
                      </tr>
                      <tr>
                        <td>
                          <strong>Rzeczywiste zakończenie wizyt:</strong>
                        </td>
                        <td>
                          <%= @appointment.actual_end.try(:localtime).try(:strftime, "%d-%m-%Y %H:%M") %>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <strong>Czas trwania wizyty:</strong>
                        </td>
                        <td>
                          <%= summary_appointment_duration @appointment %>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <strong>Ilość zdiagnozowanych chorób:</strong>
                        </td>
                        <td>
                          <%= @appointment.diseases.count %>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <strong>Ilość wypisanych recept:</strong>
                        </td>
                        <td>
                          <%= @appointment.prescriptions.count %>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <strong>Ilość przepisanych leków:</strong>
                        </td>
                        <td>
                          <%= get_appointment_midicines_count @appointment %>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <strong>Podsumowanie wizyty:</strong>
                        </td>
                        <td>
                          <%= @appointment.doctor_comment %>
                        </td>
                      </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
                <div class="col-md-6 col-xs-12">
                  <div class="panel b">
                    <div class="panel-heading">
                      <h4 class="m0">Pacjent</h4>
                      <small class="text-muted"><%= @appointment.patient.full_name %></small>
                    </div>
                    <table class="table">
                      <tbody>
                      <tr>
                        <td>
                          <strong>Imię</strong>
                        </td>
                        <td><%= @appointment.patient.first_name %></td>
                      </tr>
                      <tr>
                        <td>
                          <strong>Nazwisko</strong>
                        </td>
                        <td><%= @appointment.patient.last_name %></td>
                      </tr>
                      <tr>
                        <td>
                          <strong>Pesel</strong>
                        </td>
                        <td>
                          <%= @appointment.patient.identifier %>
                        </td>
                      </tr>
                      <% if @appointment.patient.blood_group %>
                        <tr>
                          <td>
                            <strong>Grupa krwi:</strong>
                          </td>
                          <td>
                            <%= blood_group @appointment.patient.blood_group %>
                          </td>
                        </tr>
                      <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>
        <div id="tabSetting2" class="tab-pane">
          <div class="panel b">
            <div class="panel-heading bg-gray-lighter text-bold">Rozpoznane choroby</div>
            <div class="panel-body">
              <% if @appointment.diseases.empty? %>
                <h4 class="text-center">Brak</h4>
              <% else %>
                <div class="panel b">
                  <table class="table table-striped table-hover">
                    <tbody>
                    <% @appointment.diseases.each_with_index do |disease, index| %>
                      <tr>
                        <td class=" col-xs-1 br"><%= "#{index + 1}." %></td>
                        <td><%= link_to disease.name, details_employee_diseases_path(disease),target: '_blank' %></td>
                      </tr>
                    <% end %>
                    </tbody>
                  </table>
                </div>
              <% end %>


            </div>
          </div>
        </div>
        <div id="tabSetting3" class="tab-pane">
          <div class="panel b">
            <div class="panel-heading bg-gray-lighter text-bold">Wypisane recepty</div>
            <div class="panel-body">
              <% if @appointment.prescriptions.blank? %>
                <h4 class="text-center">Brak</h4>
              <% end %>
              <% @appointment.prescriptions.each_with_index do |prescription, index| %>
                <div class="panel b">
                  <div class="panel-heading">
                    <h4 class="m0"><%= "#{index + 1}. Recepta" %></h4>
                    <br/>
                    <% if prescription.description.present? %>
                      <strong>Komentarz: </strong><%= prescription.description %>
                    <% end %>
                  </div>
                  <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                      <td><strong>Nr.</strong></td>
                      <td><strong>Nazwa</strong></td>
                      <td><strong>Moc</strong></td>
                      <td><strong>Ilość</strong></td>
                      <td><strong>Substancja aktywna</strong></td>
                      <td><strong>Komentarz</strong></td>
                    </tr>
                    </thead>
                    <tbody>
                    <% prescription.prescription_medicines.each_with_index do |medicine, index| %>
                      <tr>
                        <td><%= "#{index + 1}." %></td>
                        <td><%= link_to medicine.medicine.name, employee_medicine_path(medicine.medicine, from_summary: @appointment.id), target: '_blank' %></td>
                        <td><%= medicine.medicine.strength %></td>
                        <td><%= medicine.quantity %></td>
                        <td><%= medicine.medicine.active_substance %></td>
                        <td><%= medicine.comment %></td>
                      </tr>
                    <% end %>
                    </tbody>
                  </table>

                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% if @appointment.status == 'incoming' %>
      <%= form_for [:employee, @appointment], method: 'put' do |f| %>
        <%= f.hidden_field :status, value: 'ended' %>
        <%= f.submit 'Zakończ wizytę', class: "btn btn-success btn-block" %>
      <% end %>
    <% end %>
  </div>
</div>