config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  authenticate :employee do
    mount Sidekiq::Web => '/sidekiq'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # defaults to dashboard
  root :to => 'singleview#index'

  # view routes
  get '/singleview' => 'singleview#index'

  # api routes
  get '/api/i18n/:locale' => 'api#i18n'

  namespace :employee do
    root 'dashboard#welcome'
    resources :employments
    resources :patients do
      get :appointments, to: 'appointments#patient_appointments'
    end
    resources :employees do
      get :doctors, on: :collection
      resources :appointments, only: [:index, :edit]
      post 'appointments-doctors', on: :collection
      get 'appointments', on: :collection
      resources :day_schedules
      member do
        get 'work-schedule', to: 'employees#work_schedule'
      end
    end
    resources :appointments, only: [:create, :update, :destroy, :show] do
      post :generate_appointments, path: 'generate-appointments', on: :collection
      post :day_appointments, path: 'day-appointments', on: :collection
      get :summary, on: :member
      put :cancel, on: :member
      get :incoming, on: :collection
    end
    get :appointments, to: 'appointments#appointments'
    resources :medicines do
      get 'fetch-from-csv', on: :collection
      post 'parse-csv', on: :collection
    end
    resources :specific_diseases, path: 'specific-diseases', only: [:index, :edit, :show, :update, :destroy]
    resources :diseases, only: [:index, :show, :edit, :create, :destroy, :update] do
      collection do
        get :import
        get 'specific-diseases', to: 'diseases#specific_diseases'
        post 'parse-xml'
        get '/:id/new', to: 'diseases#new', as: :new
        get '/:id/details', to: 'diseases#details', as: :details
        get '/new', to: 'diseases#new', as: :new_root
        post '/:id', to: 'diseases#create', as: :create
        post '/', to: 'diseases#create', as: :create_root
        get '/:id/edit', to: 'diseases#edit', as: :edit
        #   get '/new', to: 'diseases#new', as: :new_root
        get '/edit', to: 'diseases#new', as: :edit_root
        #   get '/*code', to: 'diseases#show', as: :show
        #
      end

    end
    get 'reports/doctors'
    get 'reports/patients'
    post 'reports/patient_report'


  end

  namespace :patient do
    root 'dashboard#index'
    resources :appointments, only: [:index, :update] do
      get :make_appointment, on: :collection, path: 'make-appointment'
      post :day_appointments, on: :collection, path: 'day-appointments'
      put :cancel, on: :member
      get :summary, on: :member
    end
    resources :dashboard, only: [:index]
    resources :employees, except: [:index, :new, :create, :update, :edit, :destroy, :show] do
      get :work_schedules, on: :collection, path: 'work-schedules'
      get :show_work_schedule, on: :member, path: 'work-schedule'
      post :doctors_who_has_appointments, on: :collection, path: 'doctors-who-has-appointments'
      resources :day_schedules, only: [:index]
    end
    resources :medicines, only: [:index, :show]
    resources :diseases, only: [:index, :show] do
      collection do
        get '/:id/details', to: 'diseases#details', as: :details
      end
    end
    get 'reports/patients'
    post 'reports/patient_report'
  end
  devise_for :employees, path: 'employee', controllers: {sessions: 'employee/sessions'}
  devise_for :patients, path: 'patient', controllers: {sessions: 'patient/sessions'}

end

app/views/layouts/partials/_flash_msg.html.erb
<div class="alerts-container">
  <% flash.each do |message_type, message| %>
      <div data-notify="" data-onload="" data-message="<em class='<%= notify_icon(notify_status(message_type)) %>'></em> <%= message %>" data-options="{&quot;status&quot;:&quot;<%= notify_status(message_type) %>&quot;}"></div>
  <% end %>
</div>

app/views/layouts/partials/_footer.html.erb
<span>&copy; 2019 - LifeCure</span>

app/views/layouts/partials/_patient_topnavbar.html.erb
<!-- START Top Navbar-->
<nav role="navigation" class="navbar topnavbar">
  <!-- START navbar header-->
  <div class="navbar-header">
    <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="navbar-toggle">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a href="#/" class="navbar-brand">
      <div class="brand-logo">
        <img src="<%= image_path('angle/logo.png') %>" alt="App Logo" class="img-responsive"/>
      </div>
      <div class="brand-logo-collapsed">
        <img src="<%= image_path('angle/logo-single.png') %>" alt="App Logo" class="img-responsive"/>
      </div>
    </a>
  </div>
  <!-- END navbar header-->
  <!-- START Nav wrapper-->
  <div class="navbar-collapse collapse">
    <!-- START Left navbar-->
    <ul class="nav navbar-nav">
      <li></li>
      <li class="<%= 'active' if controller?('patient/appointmnets') && action?('make_appointment') %>">
        <%= link_to 'Umów wizytę', make_appointment_patient_appointments_path %>
      </li>
      <li class="<%= 'active' if controller?('widgets') && action?('index') %>">
        <%= link_to 'Przeglądaj swoje wizyty', patient_appointments_path %>
      </li>
      <li class="<%= 'active' if controller?('patient/employees') && (action?('work-schedules') or action?('work-schedule')) %>">
        <%= link_to 'Harmonogramy pracy lekarzy', work_schedules_patient_employees_path %>
      </li>
      <li class="<%= 'active' if controller?('patient/reports') && (action?('patients')) %>">
        <%= link_to 'Raport pacjenta', patient_reports_patients_path %>
      </li>


      <li><a href="#dashboard" data-toggle="dropdown">Słowniki</a>
        <ul class="dropdown-menu animated fadeIn">

          <li class="<%= 'active' if controller?('patient/medicines') %>">
            <%= link_to 'Baza lekarstw', patient_medicines_path %>
          </li>
          <li class="<%= 'active' if controller?('patient/diseases') %>">
            <%= link_to 'Baza chorób', patient_diseases_path %>
          </li>
        </ul>
      </li>

    </ul>
    <!-- END Left navbar-->
    <!-- START Right Navbar-->
    <ul class="nav navbar-nav navbar-right">
      <!-- Search icon-->
      <li class="dropdown dropdown-list">
        <a href="#" data-toggle="dropdown">
          <em class="icon-options"></em>
        </a>
        <!-- START Dropdown menu-->
        <ul class="dropdown-menu animated flipInX">
          <li>
            <!-- START list group-->
            <div class="list-group">
              <!-- list item-->


              <a href="/patient/sign_out" data-method="delete" class="list-group-item">
                <div class="media-box">
                  <div class="pull-left">
                    <em class="icon-logout text-info"></em>
                  </div>
                  <div class="media-box-body clearfix">
                    <p class="m0">Wyloguj</p>
                  </div>
                </div>
              </a>
            </div>
            <!-- END list group-->
          </li>
        </ul>
        <!-- END Dropdown menu-->
      </li>
    </ul>
    <!-- END Right Navbar-->
  </div>
  <!-- END Nav wrapper-->
  <!-- START Search form-->

  <!-- END Search form-->
</nav>
<!-- END Top Navbar-->

app/views/layouts/partials/_sidebar.html.erb
<!-- START Sidebar (left)-->
<div class="aside-inner">
  <nav class="sidebar">
    <% if current_employee.admin? %>
      <%= render partial: 'layouts/partials/menu/employee/admin_menu' %>
    <% elsif current_employee.doctor? %>
      <%= render partial: 'layouts/partials/menu/employee/doctor_menu' %>
    <% else %>
      <%= render partial: 'layouts/partials/menu/employee/receptionist_menu' %>
    <% end %>

  </nav>
</div>
<!-- END Sidebar (left)-->

app/views/layouts/partials/_topnavbar.html.erb
<!-- START Top Navbar-->
<nav role="navigation" class="navbar topnavbar">
  <!-- START navbar header-->
  <div class="navbar-header">
    <a href="/employee/dashboard/welcome" class="navbar-brand">
      <div class="brand-logo">
        <img src="<%= image_path('angle/logo.png') %>" alt="App Logo" class="img-responsive"/>
      </div>
      <div class="brand-logo-collapsed">
        <img src="<%= image_path('angle/logo-single.png') %>" alt="App Logo" class="img-responsive"/>
      </div>
    </a>
  </div>
  <!-- END navbar header-->
  <!-- START Nav wrapper-->
  <div class="nav-wrapper">
    <!-- START Left navbar-->
    <ul class="nav navbar-nav">
      <li>
        <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
        <a href="#" data-toggle-state="aside-collapsed" class="hidden-xs">
          <em class="fa fa-navicon"></em>
        </a>
        <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
        <a href="#" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
          <em class="fa fa-navicon"></em>
        </a>
      </li>
    </ul>
    <!-- END Left navbar-->
    <!-- START Right Navbar-->
    <ul class="nav navbar-nav navbar-right">
      <!-- Search icon-->
      <% if can? :generate_appointments, Appointment %>
        <li>
          <%= navigation_link generate_appointments_employee_appointments_path, '', 'icon-cloud-download', 'post' %>
        </li>
      <% end %>
      <li class="dropdown dropdown-list">
        <a href="#" data-toggle="dropdown">
          <em class="icon-options"></em>
        </a>
        <!-- START Dropdown menu-->
        <ul class="dropdown-menu animated flipInX">
          <li>
            <!-- START list group-->
            <div class="list-group">
              <!-- list item-->


              <a href="/employee/sign_out" data-method="delete" class="list-group-item">
                <div class="media-box">
                  <div class="pull-left">
                    <em class="icon-logout text-info"></em>
                  </div>
                  <div class="media-box-body clearfix">
                    <p class="m0">Wyloguj</p>
                  </div>
                </div>
              </a>
            </div>
            <!-- END list group-->
          </li>
        </ul>
        <!-- END Dropdown menu-->
      </li>
    </ul>
    <!-- END Right Navbar-->
  </div>
  <!-- END Nav wrapper-->
  <!-- START Search form-->
  <!-- END Search form-->
</nav>
<!-- END Top Navbar-->